import type { Prompt } from '../types';

export const systemPrompts: Prompt[] = [
  // --- REFLECTION (20) ---
  { id: 'p1', text: 'What is one thing you did today that you are proud of, no matter how small?', category: 'reflection', isCustom: false },
  { id: 'p2', text: 'Describe a moment today where you felt genuinely at peace.', category: 'reflection', isCustom: false },
  { id: 'p6', text: 'What pattern do you notice in your thoughts when you feel overwhelmed?', category: 'reflection', isCustom: false },
  { id: 'p15', text: 'Write about a person who made you feel safe. What did they do that created that feeling?', category: 'reflection', isCustom: false },
  { id: 'p19', text: 'What lesson have you learned this month that you want to remember?', category: 'reflection', isCustom: false },
  { id: 'p21', text: 'Write about a place where you feel completely yourself. What makes it special?', category: 'reflection', isCustom: false },
  { id: 'p27', text: 'Write about a time you surprised yourself with your own strength.', category: 'reflection', isCustom: false },
  { id: 'p31', text: 'What is a recurring dream or thought you’ve had recently? What do you think it means?', category: 'reflection', isCustom: false },
  { id: 'p32', text: 'How has your relationship with yourself evolved over the last year?', category: 'reflection', isCustom: false },
  { id: 'p33', text: 'What are three traits you admire in yourself?', category: 'reflection', isCustom: false },
  { id: 'p34', text: 'If your day today was a movie, what would the closing scene be?', category: 'reflection', isCustom: false },
  { id: 'p35', text: 'What made you laugh today? Really laugh?', category: 'reflection', isCustom: false },
  { id: 'p36', text: 'When was the last time you felt truly understood? What happened?', category: 'reflection', isCustom: false },
  { id: 'p37', text: 'What is one thing you’ve been holding onto that you’re ready to let go of?', category: 'reflection', isCustom: false },
  { id: 'p38', text: 'Describe a mistake you made that taught you something valuable.', category: 'reflection', isCustom: false },
  { id: 'p39', text: 'What does "home" mean to you right now?', category: 'reflection', isCustom: false },
  { id: 'p40', text: 'If you could revisit one conversation from today and say something different, what would it be?', category: 'reflection', isCustom: false },
  { id: 'p41', text: 'What is the most beautiful thing you saw today?', category: 'reflection', isCustom: false },
  { id: 'p42', text: 'How do you handle silence? Do you seek it out or avoid it?', category: 'reflection', isCustom: false },
  { id: 'p43', text: 'What is one question you’re currently asking yourself?', category: 'reflection', isCustom: false },

  // --- GROWTH (20) ---
  { id: 'p3', text: 'What would you tell your younger self about the challenges you faced this week?', category: 'growth', isCustom: false },
  { id: 'p8', text: 'What is one small habit you could start tomorrow that would make your mornings calmer?', category: 'growth', isCustom: false },
  { id: 'p11', text: 'Describe a fear you overcame in the past. What did you learn from it?', category: 'growth', isCustom: false },
  { id: 'p14', text: 'What is something you have been avoiding? What is the smallest step you could take toward it?', category: 'growth', isCustom: false },
  { id: 'p20', text: 'If you had no fear, what would you do differently tomorrow?', category: 'growth', isCustom: false },
  { id: 'p23', text: 'Think of a mistake you made recently. What would a compassionate friend say about it?', category: 'growth', isCustom: false },
  { id: 'p28', text: 'If your future self could send you a message, what would it say?', category: 'growth', isCustom: false },
  { id: 'p44', text: 'What is a skill you’d love to learn merely for the joy of it?', category: 'growth', isCustom: false },
  { id: 'p45', text: 'Write about a time you stood up for yourself. How did it feel?', category: 'growth', isCustom: false },
  { id: 'p46', text: 'What does "success" mean to you in this stage of your life?', category: 'growth', isCustom: false },
  { id: 'p47', text: 'Identify one area where you’re being too hard on yourself. Can you offer yourself some grace today?', category: 'growth', isCustom: false },
  { id: 'p48', text: 'What is one piece of advice you’ve received that has actually changed your life?', category: 'growth', isCustom: false },
  { id: 'p49', text: 'If you could have a conversation with your 80-year-old self, what would you ask?', category: 'growth', isCustom: false },
  { id: 'p50', text: 'What is a boundary you’re proud of setting recently?', category: 'growth', isCustom: false },
  { id: 'p51', text: 'How do you want people to feel when they are around you?', category: 'growth', isCustom: false },
  { id: 'p52', text: 'What is the biggest risk you’ve ever taken? Was it worth it?', category: 'growth', isCustom: false },
  { id: 'p53', text: 'Write about a time you failed and how you eventually bounced back.', category: 'growth', isCustom: false },
  { id: 'p54', text: 'What is one thing you can do this week to step outside your comfort zone?', category: 'growth', isCustom: false },
  { id: 'p55', text: 'Who is someone whose life path inspires you? Why?', category: 'growth', isCustom: false },
  { id: 'p56', text: 'What is one thing you want to be known for?', category: 'growth', isCustom: false },

  // --- GRATITUDE (20) ---
  { id: 'p7', text: 'Write a letter to someone you appreciate but haven\'t told recently.', category: 'gratitude', isCustom: false },
  { id: 'p16', text: 'Name five things that went right today, even if they seem insignificant.', category: 'gratitude', isCustom: false },
  { id: 'p25', text: 'List three people who positively impacted your life this year.', category: 'gratitude', isCustom: false },
  { id: 'p30', text: 'What are you most grateful for in this exact moment?', category: 'gratitude', isCustom: false },
  { id: 'p57', text: 'What is one physical object you own that brings you immense joy?', category: 'gratitude', isCustom: false },
  { id: 'p58', text: 'Write about a "small win" from today.', category: 'gratitude', isCustom: false },
  { id: 'p59', text: 'What is a part of your daily routine that you genuinely appreciate?', category: 'gratitude', isCustom: false },
  { id: 'p60', text: 'Recall a time someone was unexpectedly kind to you.', category: 'gratitude', isCustom: false },
  { id: 'p61', text: 'What is something beautiful about your neighborhood or home?', category: 'gratitude', isCustom: false },
  { id: 'p62', text: 'What are you grateful for about your body today?', category: 'gratitude', isCustom: false },
  { id: 'p63', text: 'List three things that always put a smile on your face.', category: 'gratitude', isCustom: false },
  { id: 'p64', text: 'Who is a teacher or mentor you are thankful for?', category: 'gratitude', isCustom: false },
  { id: 'p65', text: 'What is a song that always lifts your spirits?', category: 'gratitude', isCustom: false },
  { id: 'p66', text: 'Describe a meal you had recently that you thoroughly enjoyed.', category: 'gratitude', isCustom: false },
  { id: 'p67', text: 'What is one technology or tool that makes your life easier?', category: 'gratitude', isCustom: false },
  { id: 'p68', text: 'Write about a time you felt really lucky.', category: 'gratitude', isCustom: false },
  { id: 'p69', text: 'What is a book, movie, or art piece that has positively impacted you?', category: 'gratitude', isCustom: false },
  { id: 'p70', text: 'What part of nature do you feel most connected to?', category: 'gratitude', isCustom: false },
  { id: 'p71', text: 'Write about a seasonal change you enjoy.', category: 'gratitude', isCustom: false },
  { id: 'p72', text: 'What is one thing you’ve learned recently that you’re grateful to know?', category: 'gratitude', isCustom: false },

  // --- SELF-CARE & WELLBEING (20) ---
  { id: 'p5', text: 'Write about three things you can see, two you can hear, and one you can touch right now.', category: 'self-care', isCustom: false },
  { id: 'p10', text: 'What boundaries do you need to set this week to protect your energy?', category: 'self-care', isCustom: false },
  { id: 'p12', text: 'What are three sounds you can hear right now? How do they make you feel?', category: 'self-care', isCustom: false },
  { id: 'p17', text: 'What does your body need right now? Rest, movement, nourishment, or connection?', category: 'self-care', isCustom: false },
  { id: 'p22', text: 'What is one kind thing you can do for yourself today?', category: 'self-care', isCustom: false },
  { id: 'p26', text: 'What is your body holding onto right now? Where do you feel tension?', category: 'self-care', isCustom: false },
  { id: 'p73', text: 'If you could spend a whole day doing absolutely nothing, how would you start?', category: 'self-care', isCustom: false },
  { id: 'p74', text: 'What is your favorite way to decompress after a long day?', category: 'self-care', isCustom: false },
  { id: 'p75', text: 'Write about a scent that makes you feel calm.', category: 'self-care', isCustom: false },
  { id: 'p76', text: 'What is the most nourishing thing you could say to yourself right now?', category: 'self-care', isCustom: false },
  { id: 'p77', text: 'Describe your perfect morning routine if time and money were no object.', category: 'self-care', isCustom: false },
  { id: 'p78', text: 'What is a hobby you lost touch with that you’d like to pick back up?', category: 'self-care', isCustom: false },
  { id: 'p79', text: 'When did you last feel truly rested?', category: 'self-care', isCustom: false },
  { id: 'p80', text: 'How do you want to feel at the end of this week?', category: 'self-care', isCustom: false },
  { id: 'p81', text: 'Write about a physical space that makes you feel safe and relaxed.', category: 'self-care', isCustom: false },
  { id: 'p82', text: 'What is one thing you can say "no" to this week to create more space?', category: 'self-care', isCustom: false },
  { id: 'p83', text: 'List five things you can do to be kinder to your body.', category: 'self-care', isCustom: false },
  { id: 'p84', text: 'What does "rest" look like for you beyond just sleep?', category: 'self-care', isCustom: false },
  { id: 'p85', text: 'Write about a comfort food that feels like a hug.', category: 'self-care', isCustom: false },
  { id: 'p86', text: 'What is a phrase or mantra that helps you stay grounded?', category: 'self-care', isCustom: false },

  // --- CREATIVITY & IMAGINATION (20) ---
  { id: 'p4', text: 'If your anxiety had a shape and color, what would it look like? Describe it in detail.', category: 'creativity', isCustom: false },
  { id: 'p9', text: 'Imagine your ideal day from start to finish. What does it look like?', category: 'creativity', isCustom: false },
  { id: 'p13', text: 'If you could give today a title like a book chapter, what would it be?', category: 'creativity', isCustom: false },
  { id: 'p18', text: 'Describe your current emotional weather — is it stormy, sunny, foggy, or calm?', category: 'creativity', isCustom: false },
  { id: 'p24', text: 'What color represents your mood right now, and why?', category: 'creativity', isCustom: false },
  { id: 'p29', text: 'Describe your happiest memory using all five senses.', category: 'creativity', isCustom: false },
  { id: 'p87', text: 'If you were an element (water, air, earth, fire), which one would you be today? Why?', category: 'creativity', isCustom: false },
  { id: 'p88', text: 'Write a short story about a version of you who lives in a parallel universe.', category: 'creativity', isCustom: false },
  { id: 'p89', text: 'If you could visit any planet, which one would it be and what would you do there?', category: 'creativity', isCustom: false },
  { id: 'p90', text: 'What would your personal logo look like? What symbols would it include?', category: 'creativity', isCustom: false },
  { id: 'p91', text: 'Describe a dream world where all your needs are automatically met.', category: 'creativity', isCustom: false },
  { id: 'p92', text: 'If your life was a garden, what kind of flowers or plants would be growing in it right now?', category: 'creativity', isCustom: false },
  { id: 'p93', text: 'Write a dialogue between your "Fear" and your "Courage."', category: 'creativity', isCustom: false },
  { id: 'p94', text: 'Imagine a super-power that perfectly complements your personality.', category: 'creativity', isCustom: false },
  { id: 'p95', text: 'What would a soundtrack of your life sound like?', category: 'creativity', isCustom: false },
  { id: 'p96', text: 'Describe a fictional character who feels like a soulmate. Why?', category: 'creativity', isCustom: false },
  { id: 'p97', text: 'If you could build a secret hideout anywhere in the world, where would it be?', category: 'creativity', isCustom: false },
  { id: 'p98', text: 'Write about a color that doesn’t exist. How would it feel to see it?', category: 'creativity', isCustom: false },
  { id: 'p99', text: 'If you could communicate with animals, which one would you talk to first?', category: 'creativity', isCustom: false },
  { id: 'p100', text: 'Describe a futuristic version of your favorite hobby.', category: 'creativity', isCustom: false },
];

export function getPromptOfTheDay(): Prompt {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000
  );
  // Get all system prompts
  return systemPrompts[dayOfYear % systemPrompts.length];
}
